# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vjt-zendesk}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcello Barnaba"]
  s.date = %q{2011-05-19}
  s.description = %q{The plugin implements the HTML generation code for the Zendesk dropbox and the necessary controller and routing code to implement remote authentication}
  s.email = %q{vjt@openssl.it}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "lib/zendesk.rb",
    "lib/zendesk/controller.rb",
    "lib/zendesk/helpers.rb",
    "lib/zendesk/railtie.rb",
    "lib/zendesk/routing.rb",
    "lib/zendesk/version.rb"
  ]
  s.homepage = %q{http://github.com/vjt/zendesk}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Zendesk on Rails - Dropbox and Remote Authentication}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0"])
  end
end

